ROJECT="paper"
VERSION="${MC_VERSION:-1.21.11}"
TYPE=stable

#Check downloads with sha256sum
SHA256=True

#Server List, you can add more
SERVER=()
SERVER_DIR=()

AUTO_UPGRADE="${AUTO_UPGRADE:-false}"   # true / false

CURRENT_BUILD="${CURRENT_BUILD:-0}"
CURRENT_CHANNEL="${CURRENT_CHANNEL:-ALPHA}
